### ISSUE TITLE
AddressBookParser - Concurrency issue

### ISSUE THREAD

**Issue by dclarke18** [dclarke18/Gumtree-AddressBook#5]
I'm just about to commit a test case to prove the issue but AddressBookParser is failing when a single instance is used by multiple threads.
Haven't started diagnosis - will push the test case which replicates the problem.

`java.lang.ArrayIndexOutOfBoundsException: 1
    at org.apache.commons.csv.CSVRecord.get(CSVRecord.java:81)
    at uk.co.blc_services.gumtree.AddressBookParser.parse(AddressBookParser.java:46)
    at uk.co.blc_services.gumtree.AddressBookParserConcurrencyTest.testParse(AddressBookParserConcurrencyTest.java:74)`

**Comment by dclarke18** [comment]
It appears that there may be a bug in the test. It seems that the inputstream is being closed before the 2nd thread completes it's execution. The is shouldn't be being shared... Ah but it is!.
